language: python

python:
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get install redis-server
  - sudo service redis-server start
  - redis-server --version
  - which redis-server
  - /bin/sleep 10

install:
  - "pip install . --use-mirrors"

script: ./tests.py

env:
  matrix:
  - "REDIS_PORT=6379"
  - "START_REDIS_SERVER=True REDIS_PORT=0 REDIS_HOST=/tmp/asyncio"
